export const plans = [
  {
    id: "0",
    title: "Starter",
    priceMonthly: 2500,
    priceYearly: 2000,
    caption: "Perfect for small businesses",
    features: [
      "Landing page design",
      "Responsive development",
      "Basic SEO optimization",
      "3 months support",
    ],
    icon: "circle",
  },
  {
    id: "1",
    title: "Professional",
    priceMonthly: 5000,
    priceYearly: 4000,
    caption: "Most popular package",
    features: [
      "Custom web application",
      "Database integration",
      "User authentication",
      "6 months support",
      "Mobile responsive",
    ],
    icon: "triangle",
  },
  {
    id: "2",
    title: "Enterprise",
    priceMonthly: 10000,
    priceYearly: 8000,
    caption: "For large organizations",
    features: [
      "Full-stack development",
      "Microservices architecture",
      "Cloud deployment",
      "12 months support",
      "Team training included",
    ],
    icon: "hexagon",
  },
];
